### ISSUE TITLE
Update package on NPM

### ISSUE THREAD

**Issue by sagiavinash** [zenoamaro/react-quill#124] opened 2016-10-02 14:10 UTC
the latest module distributed via npm is react-quill(v0.4.1) but it has quill v0.2.
But the latest source on `master` branch's package.json shows quill 1.0.

Please release the latest dist of react-quill on npm.

**Comment by eskawl** [comment] 2016-10-04 13:33
#121

**Comment by zenoamaro** [comment] 2016-10-19 22:01
Duplicate of #121.

**Closed by zenoamaro** 2016-10-19 22:01 UTC
