### ISSUE TITLE
The version of react-quill on www.npmjs.com is too old

### ISSUE THREAD

**Issue by zhanxia** [zenoamaro/react-quill#127] opened 2016-10-24 07:07 UTC
when i run npm install in my project,The version of react-quill in my node_modules is 0.4.1,so i can't use the image local upload feature in my project.How do I use the image local upload feature?

**Comment by alexkrolick** [comment] 2016-10-25 04:58
Duplicate of https://github.com/zenoamaro/react-quill/issues/113

**Comment by zenoamaro** [comment] 2017-02-07 21:00
Please see #113 for release updates.

**Closed by zenoamaro** 2017-02-07 21:00 UTC
