### ISSUE TITLE
Multiple toolbars with hot reloading

### ISSUE THREAD

**Issue by jiayihu** [zenoamaro/react-quill#172] opened 2017-03-16 08:53 UTC
With hot reloading a new toolbar is appended after each update. In the screenshot there is only one at the bottom, but the number can increase. I think something wrong happens while checking for new props passed to the component, probably in `componentWillReceiveProps`.

![schermata 2017-03-16 alle 09 51 15](https://cloud.githubusercontent.com/assets/10067273/23988366/4405db5a-0a2e-11e7-9964-579563ac0b95.png)

Quill version: 
- [ ] master
- [ ] 0.4.1
- [x] 1.0.0-beta-3
- [ ] Other (fork)

**Comment by zenoamaro** [comment] 2017-03-16 08:54
Duplicate of #147

**Closed by zenoamaro** 2017-03-16 08:54 UTC
