### ISSUE TITLE
Crawling with bugs. Does anyone use this in production?

### ISSUE THREAD

**Issue by MitchEff** [zenoamaro/react-quill#522] opened 2019-09-13 07:04 UTC
Look, I cannot fathom why I've had so much trouble setting up Quill. I can't even paste in a list, and my users are reporting a bunch of other random bugs. 

So, I've copied [this CodePen](https://codepen.io/alexkrolick/pen/xgyOXQ?editors=0010#0) **identically** into my project. Literally the only change is exporting it, rather than mounting on the `div` at the bottom.

Same methods, same absolutely everything. Latest versions of everything - Quill v1.3.6 and ReactQuill v1.3.1.

- I cannot copy text from [Quill's own changelog](https://github.com/quilljs/quill/blob/develop/CHANGELOG.md) - the half the list items disappear. 
- I cannot copy lists from OSX's 'Notes' app. It just makes a ton of white space. This works totally fine in a `textarea`, `contentEditable div`, etc etc. It's just a list. 
- In fact, I can't even copy text from a Google search, the whole app crashes.

My console reports:
- Generally nothing. Just removes any lists, and throws in 20-30 `<br />` tags, for some reason
- Sometimes `Cannot read property 'emit' of undefined at Scroll.update (quill.js:4329)`
- Sometimes `The given range isn't in document`

I no longer care _why_ this is a buggy nightmare, I just need it to be useable - if anyone's prepared to fix this for me I'm genuinely happy to pay. Apologies for the tone, I've just spent way too long on this.

**Comment by r0jer** [comment] 2019-09-20 15:05
I had the emit error in a slightly different place. It was caused by interacting with Quill before it was fully initialised.

**Comment by MitchEff** [comment] 2019-10-16 10:35
Oh my GOD. 

Okay, I've worked out most of these issues. Do _not_ set '.ql-clipboard' to 'display: none;'.
All hell breaks loose. I don't recall why I did in the first place.

**Comment by zenoamaro** [comment] 2020-03-29 19:55
I am sorry you had such an experience! I hope things are working better now.

Closing as resolved

**Closed by zenoamaro** 2020-03-29 19:55 UTC

**Comment by zehawki** [comment] 2020-05-23 08:28
> Crawling with bugs.

That's an unfair statement :-) Its stable and works very well. Its being used for:

1. Creating content
2. Editing existing content
3. With Quill Toolbar and format modules
4. Also integrated with dropzone for image handling

>Does anyone use this in production?

Yup, we do, Heavily.
