### ISSUE TITLE
update with npm not working

### ISSUE THREAD

**Issue by mouhsinelonly** [zenoamaro/react-quill#121] opened 2016-09-22 19:37 UTC
i tried to update the package with npm update but with no luck

**Comment by alexkrolick** [comment] 2016-09-22 19:53
The NPM version hasn't been bumped yet due to a need to specify a migration path for existing installs.

@zenoamaro on the other hand, I bumped the major version in package.json, so it wouldn't break semver to push an update to NPM.

**Comment by mouhsinelonly** [comment] 2016-09-22 19:55
existing installs could stay on the old version, as no one is forced to make an update ?

**Comment by jhaddow** [comment] 2016-10-05 23:10
Any chance you can branch off the current version that is published on npm so we can look through the source code of that version here on GitHub?

**Comment by tomaash** [comment] 2016-10-17 14:57
@zenoamaro can you please release current master to NPM? As major version has been updated already in package.json, it should not break semver for anyone.

**Comment by zenoamaro** [comment] 2016-10-19 22:05
Duplicate of #113.

**Closed by zenoamaro** 2016-10-19 22:05 UTC
