### ISSUE TITLE
[v2] Uncaught Invariant Violation: Maximum update depth exceeded

### ISSUE THREAD

**Issue by xeger** [zenoamaro/react-quill#585] opened 2020-04-07 00:16 UTC
I'm sorry I can't give you a clean reproduction on this; it only happens when using Cypress to automate my tests, and even then, only in particular circumstances involving a lot of prior tests having been run.

The React exception message looks like so:

![image](https://user-images.githubusercontent.com/73368/78616532-526ba500-7829-11ea-99a2-9e77198ceb46.png)

(Ignore the latter paragraphs; the React exception message is the entirety of the first paragraph.)

My suspicion is that my application's heavy use of MobX and controlled props is causing a feedback loop, as evidenced by this snippet of my own application code:

![image](https://user-images.githubusercontent.com/73368/78616693-c8700c00-7829-11ea-9ab5-47a0a6ad27f3.png)

I can't explain why the feedback loop only happens while running automated tests ... perhaps you or quill have got some idempotency/loop-detection type stuff and it's being foiled in that environment.

I am currently rewriting the offending components of my app to be simpler and uncontrolled, which will likely work around whatever issue is occurring. I wanted to raise this issue with you, however, since ReactQuill v2 is in its beta period and you might have an "ah-hah" realization about how to prevent this feedback loop.

If I have any more time to dedicate to it, I will try to create a standalone repro for you.

**Comment by alexkrolick** [comment] 2020-04-07 18:52
Are you passing the Quill delta back into the component instead of the HTML? There is a warning about that.

**Comment by smnscp** [comment] 2020-04-08 10:43
Hi @xeger, could you take a closer look at your initial `self.value` you’re passing to the component’s `value`?

I encountered a similar problem with a re-render loop. Turns out it is related to line-breaks, especially between paragraphs and lists. I could reproduce the issue with the following minimal example:

```js
import React, {useState} from 'react'
import ReactQuill from 'react-quill'

export const ReactQuillTest = () => {
  const [testText, setTestText] = useState("<p>Lorem</p><ul><li>ipsum</li></ul>")

  return <>
    <ReactQuill value={testText} onChange={(html) => {console.log(testText, html); setTestText(html)}} />
    <p>{testText}</p>
  </>
}
```

Here, the component keeps inserting `<p><br></p>` before the `<ul>`:

```html

<p>Lorem</p><ul><li>ipsum</li></ul>
<p>Lorem</p><p><br></p><ul><li>ipsum</li></ul>
<p>Lorem</p><p><br></p><p><br></p><ul><li>ipsum</li></ul>
…

```

**Comment by smnscp** [comment] 2020-04-08 10:47
BTW: What solved it for me was to use `ReactQuill` in uncontrolled mode. Documentation mentions [controlled mode caveats](https://github.com/zenoamaro/react-quill#controlled-mode-caveats).

**Comment by xeger** [comment] 2020-04-08 15:21
Interesting; I copy-pasted @smnscp's reproduction into my source file in place of my own `ReactQuill` invocation, and the problem didn't reproduce.

There are some similarities between me and you: I'm using `ReactQuill` in controlled mode; I am both consuming and `value=`'ing the Quill HTML content, as opposed to the deltas. However, to @alexkrolick's point, my `value=` prop assignment is guarded by a function `isContentBlank` that _reads_ the editor's delta to make a decision:

```
const isContentBlank = editor =>
  editor.getLength() === 1 ||
  (editor.getContents().ops.length === 1 && isBlank(editor.getText()));
```

So: upon rendering `ReactQuill` I'm reading both the protected editor's deltas and text, _and_ I am consuming its HTML (and feeding that back to the editor's `value` as an HTML string, or sometimes a blank string).

If I stub `isContentBlank` to always return false, the issue stops reproducing. So, it has something to do with using `ReactQuill` in controlled mode _and_ consuming its delta and text output.

If I change the ordering so that `editor.getHTML` is called first, the problem still reproduces.

Perhaps most curious of all: the problem _only_ reproduces during the first iteration of my tests in a given browser process. If I re-run the tests, the problem stops reproducing -- even though Cypress is entirely reloading the React app in its embedded testing iframe.

So, this issue seems to involve a race condition that is impacted by V8 behavior -- JIT compilation perhaps, or caching of some sort at any rate.

Here is the relevant stack trace FWIW:
```
    at checkForNestedUpdates (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23118:7)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21389:3)
    at Object.enqueueSetState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:13100:5)
    at ReactQuill.Component.setState (webpack-internal:///./node_modules/react/cjs/react.development.js:325:16)
    at ReactQuill.onEditorChangeText (webpack-internal:///./node_modules/react-quill/lib/index.js:371:18)
    at ReactQuill.eval (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js:714:25)
    at Emitter.ReactQuill._this.onEditorChange (webpack-internal:///./node_modules/react-quill/lib/index.js:86:96)
    at Emitter.emit (webpack-internal:///./node_modules/quill/dist/quill.js:8666:27)
    at Emitter.emit (webpack-internal:///./node_modules/quill/dist/quill.js:1938:99)
```

**Comment by zenoamaro** [comment] 2020-04-13 17:34
Hello. The management of `value` has been changed. Among other things, it might fix this issue, as it avoids triggering many renders.

It is experimentally located in this branch: https://github.com/zenoamaro/react-quill/tree/fix/direct-value-change

Any chance you could try it (eg. using `npm link`)? It is a big enough change that I'd prefer to test it out before releasing it. Thanks!

**Comment by smnscp** [comment] 2020-04-14 08:37
Hi @zenoamaro, I did a quick testing of that branch. My above `ReactQuillTest` component did work as expected without re-render loop. Thanks for the fix!

**Comment by zenoamaro** [comment] 2020-04-15 18:50
Thanks! Closing this

**Closed by zenoamaro** 2020-04-15 18:50 UTC
Labels: v2

**Comment by shinzui** [comment] 2020-05-12 18:52
It's unclear whether the fix is on master since the referenced branch is deleted.

**Comment by shinzui** [comment] 2020-05-12 18:53
We're running `2.0.0-beta.2` and are having the same problem.

**Comment by Ancinek** [comment] 2020-05-29 12:57
@shinzui What was the source of the problem? We're facing the same issue – the quill adds characters to the original value and creates an infinite loop

**Comment by robrondon** [comment] 2023-09-12 18:12
I'm having this issue trying to build a blog.. sometimes when I edit a post it breaks with `react-dom.development.min.js:1 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate.`
