### ISSUE TITLE
A problem with custom dropdown

### ISSUE THREAD

**Issue by Sprinter101** [zenoamaro/react-quill#332] opened 2018-02-21 21:51 UTC
Hi! I want to add a custom dropdown to be able to select font-weight. I also want to modify the 'size' element to have options as numbers. Here is my code:

```
  const Quill = ReactQuill.Quill;
  const Font = Quill.import('formats/font');
  Font.whitelist = ['Arial', 'Roboto'];
  Quill.register(Font, true);


  const Size = Quill.import('formats/size');
  Size.whitelist = ['8', '9', '10', '11', '12', '14', '16', '18', '24', '30', '36', '48', '60', '72', '96'];
  Quill.register(Size, true);

  const Parchment = Quill.import('parchment')
  const Weight = new Parchment.Attributor.Class()
  Weight.attrName = 'weight'
  Weight.keyName = 'ql-weight'
  Weight.scope = 5;
  Quill.register(Weight, true)

const CustomToolbar = () => (
  <div id="toolbar">
    <select className="ql-font">
      <option value="Arial" selected>Roboto</option>
      <option value="Roboto">Roboto</option>
    </select>
    <select className="ql-size">
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
      <option value="11">11</option>
      <option value="12">12</option>
      <option value="14">14</option>
      <option value="16">16</option>
      <option value="18">18</option>
      <option value="24">24</option>
      <option value="30">30</option>
      <option value="36">36</option>
      <option value="48">48</option>
      <option value="60">60</option>
      <option value="72">72</option>
      <option value="96">96</option>
    </select>
    <select className="ql-weight">
      <option value="300">300</option>
      <option value="400">400</option>
      <option value="500">500</option>
      <option value="600">600</option>
      <option value="700">700</option>
      <option value="800">800</option>
      <option selected></option>
    </select>
  </div>
)

ReactDOM.render(
  <div>
      <CustomToolbar />
      <ReactQuill
        value={props.value}
        onChange={props.onChange}
        modules={{
          toolbar: {
            container: '#toolbar',
          },
        }}
        formats={[
          'font', 'size', 'weight',
        ]}
      />
    </div>, 
  document.querySelector('.app')
)
```

The problem is I don't know how to specify the default value that would be selected in the dropdown.
Right now the dropdown is "empty" at the start and when I select a value to style a part of a text and then move to different part of a text, the dropdown displays last selected value.

The custom styling itself is working.

**Comment by alexkrolick** [comment] 2018-02-26 05:30
I think this is a dupe of #175. Unfortunately it's still unsolved.

**Comment by alexkrolick** [comment] 2018-02-26 06:23
Does this fix you issue? 

```jsx
<select className="ql-size" defaultValue={"8"} onChange={e => e.persist()}>
```

https://codepen.io/alexkrolick/pen/xYyqVo?editors=0010

**Comment by Sprinter101** [comment] 2018-02-26 14:17
Yes, that helped. The only problem now is that the custom dropdown doesn't display the values in the toolbar, but it can be solved with CSS.

SASS:
```
.ql-weight {
      .ql-picker-label:before,
      .ql-picker-item:before {
          content: attr(data-label);
      }
}
```

**Comment by alexkrolick** [comment] 2018-02-26 17:36
Yep, the themed toolbars require CSS mods for custom elements. If you turn off the theme you could style the raw HTML, but you lose some of the functions for link and color handling, etc

**Closed by alexkrolick** 2018-02-26 17:36 UTC
