### ISSUE TITLE
Toolbar `ql-align` render `selected` fail

### ISSUE THREAD

**Issue by bugkiwi** [zenoamaro/react-quill#228] opened 2017-07-07 05:42 UTC
[template]: 

https://codepen.io/bugkiwi/pen/OgoRbw?editors=1010

![image](https://user-images.githubusercontent.com/1936250/27944102-0026df82-6317-11e7-9e2d-ce23f36f1e4e.png)

### FAQ

**Toolbar `ql-align` not work well ?**

#### Quill version 
1.0.0

**Comment by alexkrolick** [comment] 2017-07-07 05:55
https://quilljs.com/docs/formats/

You need to add `align` to the array of formats

**Comment by alexkrolick** [comment] 2017-07-07 06:33
Although... you are correct that even with the format enabled it does seem to be failing to show the default value. Duplicate of: https://github.com/zenoamaro/react-quill/issues/175

**Comment by alexkrolick** [comment] 2017-07-09 23:27
Reopening as I've discovered that it's possible to fix this issue without fixing #175.

Submitted the fix upstream at #1576.

Demo of broken behaviour: https://codepen.io/alexkrolick/pen/awRxWz?editors=0010
Demo of fixed Quill: https://codepen.io/alexkrolick/pen/qjMrEN

**Comment by alexkrolick** [comment] 2017-07-10 07:32
quilljs/quill#1576 was merged

**Closed by alexkrolick** 2017-07-10 07:32 UTC

**Comment by bugkiwi** [comment] 2017-07-12 16:23
Sorry for late. 

After your first resp,  I have found there are maybe a bug on quill, and I read the Quilljs source. I found use 
```
<select className="ql-align"></select>
```
without any options will be a good choice, Quilljs will give a default options. It works well. Maybe this will help some one.

Thanks for your help:)
