### ISSUE TITLE
React 15?

### ISSUE THREAD

**Issue by dlebedynskyi** [zenoamaro/react-quill#89] opened 2016-04-11 19:50 UTC
Hi, 
it seems that react is now officially in v15 release. can you please update package deps for comparability?

**Comment by zenoamaro** [comment] 2016-04-18 17:13
Hi, I will test and upgrade to `react@15` soon.

**Comment by Tzaphkiel** [comment] 2016-04-26 16:03
I find that it breaks with react 15.0.1... 
I get empty boxes when I render the component, the toolbar fails to render the controls:
![image](https://cloud.githubusercontent.com/assets/644489/14825094/d209fc2e-0bd8-11e6-997f-b6c52de52015.png)
![image](https://cloud.githubusercontent.com/assets/644489/14825137/f14d54be-0bd8-11e6-92ba-1678531c1dd0.png)

Probably because of the following errors in the browser console:
![image](https://cloud.githubusercontent.com/assets/644489/14825113/e0be4392-0bd8-11e6-9076-321cb7cd64e1.png)

**Comment by zenoamaro** [comment] 2016-04-26 16:19
Thanks, could you check if this is still broken on `master`?

**Comment by Tzaphkiel** [comment] 2016-04-26 18:58
in master,  this might be the problem:
if (item.selected) {

attrs.defaultValue = item.value;

}

instead of setting defaultvalue,  you should just use value i think! 

I'll check tomorrow. 

~Leroy Sébastien

On 26 Apr 2016 18:19, zenoamaro <notifications@github.com> wrote:

Thanks, could you check if this is still broken on master?

**Comment by Tzaphkiel** [comment] 2016-04-27 09:10
My bad, the snow css was included but not defined in the theme prop of of the ReactQuill.

That being said, when you do not specify a theme, should you not get a default one?
If I don't specify snow and include the css, I get the rendering seen int he image above.

**Comment by michaelzoidl** [comment] 2016-04-28 12:48
+1 :)

**Comment by Predjo** [comment] 2016-05-16 10:04
+1

**Comment by michaelzoidl** [comment] 2016-05-23 08:56
FYI, i moved to the [medium-editor](https://github.com/yabwe/medium-editor).
There is also a good [react-wrapper](https://github.com/wangzuo/react-medium-editor) available.

It's not the same like quill, but for my case it was a good solution.

**Comment by zenoamaro** [comment] 2017-02-07 20:51
Hello, React Quill now uses the standard Quill toolbar, so this won't be a problem anymore. However, the issue is now fixed in the React Quill Toolbar as well.

**Closed by zenoamaro** 2017-02-07 20:51 UTC
