### ISSUE TITLE
readOnly not working correctly when you have custom button

### ISSUE THREAD

**Issue by pavel06081991** [zenoamaro/react-quill#266] opened 2017-09-11 15:35 UTC
I have custom button which adds some text:

```js
function onBrbButtonClick(this: any) {
  const cursorPosition = this.quill.getSelection().index;
  this.quill.insertText(cursorPosition, `${BRACKET_R_BRACKET_SYMBOL}`, { script: 'sup' });
  this.quill.setSelection(cursorPosition + BRACKET_R_BRACKET_SYMBOL.length);
}
```

When readOnly is true all native buttons does not work but when I click my custom button it still adds text

**Comment by alexkrolick** [comment] 2017-09-11 16:41
What are your Quill and React-Quill versions? There was a bug in Quill that was fixed in 1.1.6: https://github.com/quilljs/quill/issues/1151

**Comment by pavel06081991** [comment] 2017-09-11 17:44
@alexkrolick, I use 1.1.0

**Comment by alexkrolick** [comment] 2017-09-11 18:08
What Quill version are you resolving? If it is greater than 1.1.6 you should file a bug upstream in Quill since that API is simply exposed directly by ReactQuill.

**Comment by alexkrolick** [comment] 2017-09-16 23:35
Reproduced at https://codepen.io/alexkrolick/pen/GMprej

**Closed** 2017-09-17 18:27 UTC
Labels: upstream-quill

**Comment by ShenLanJohn** [comment] 2019-12-11 08:55
it works fine after do "npm start". please restart your ract app.
