### ISSUE TITLE
Adding Image Upload Icon fails for me

### ISSUE THREAD

**Issue by enricribas** [zenoamaro/react-quill#53] opened 2015-11-17 14:38 UTC
```
<QuillReact modules={{ 'image-tooltip': true }} theme={"snow"} value={this.state.message} onChange={this._handleTextChange} />
```

Unless I am doing something wrong, this should add the image icon to the end of the toolbar. But it seems to just show the toolbar but without image icon. 
Thanks.

**Comment by kairxa** [comment] 2015-11-19 08:50
You can add it by modifying the toolbar items. From the defaultItems array, you can add `{ type: 'image', label: 'Image' }` and then the image icon will show up. The problem is, even though it showed up, I practically can't make changes to the contentEditable area.

Most likely ReactQuill got re-rendered for whatever reason since I get the .getDOMNode warning (three warnings, actually) everytime I try to type something.

**Comment by zenoamaro** [comment] 2015-11-19 11:36
@enricribas, @brucedlukens, both the `image-tooltip` module and the toolbar item must be set for the image button to appear. This is the same as Quill. `modules={{ 'image-tooltip': true }}` should be correct, and use @kairxa's instructions to add the button to the toolbar. In the future, we'll see about adding the image button as default.

@kairxa, if you create the toolbar items array inside your `render()`, ReactQuill will re-render each time, as this is the only way to change Quill's configuration. In the future, ReactQuill will do a deeper compare so to avoid any unnecessary re-renders, but in the meantime please define the toolbar items object just once, outside your render, and always use that instance, so it won't trigger the `===` check.

**Comment by kairxa** [comment] 2015-11-19 13:14
No, I didn't create the array inside render(). All I did was merely add `modules` props when using ReactQuill, and then when I type inside the editor, it got triple rendered.

`<ReactQuill modules={ {} } />` will give you the error I mentioned.

**Comment by zenoamaro** [comment] 2015-11-19 13:24
It's the same thing, basically. Each render, a completely new instance of an object (`modules={}` in this case) is being passed as prop to ReactQuill, and this triggers the dirty prop checking, causing (correctly) a re-render of Quill to update its settings. It should be immutable.

Until a deep comparison of props gets implemented, please define the object you pass to `modules` only once, outside render; or in any case do not redefine it unless it actually changes.

**Comment by zenoamaro** [comment] 2016-02-04 21:48
The image toolbar item is now present in the default set of buttons.

It will be published to NPM soon, but it is already in `master`.

**Comment by perfectyang** [comment] 2016-03-14 04:10
how to upload local images with default image buttons ,waiting for respone online

**Comment by zenoamaro** [comment] 2017-02-07 20:18
This is fixed in the latest `master`. Deep prop comparison is now in place, and objects can safely be passed to a ReactQuill component without triggering re-renders.

**Closed by zenoamaro** 2017-02-07 20:18 UTC
