### ISSUE TITLE
How to use Parchment for formats

### ISSUE THREAD

**Issue by thewebsitedev** [zenoamaro/react-quill#151] opened 2017-02-17 13:40 UTC
Is there an example on how to use Parchment with React Quill? If not, can anyone provide one please? Thanks!

Quill version: 
1.0.0-beta-1

**Comment by alexkrolick** [comment] 2017-02-20 03:35
You can pass a `formats` array to the component that can include custom formats. See the R[EADME example](https://github.com/zenoamaro/react-quill#theming-custom-toolbar-and-formats-custom-editing-area) (excluding definition of the custom format).

**Comment by alexkrolick** [comment] 2017-02-20 07:05
This should work if you get a reference to the Quill instance: https://codepen.io/alexkrolick/pen/PWrKdx?editors=0010

It doesn't work in Codepen, I'm assuming because the ReactQuill CDN bundle and the Quill CDN bundle are attaching separate instances of Quill.

**Comment by tdg5** [comment] 2017-02-22 19:33
I can confirm that @alexkrolick's examples are a good example of how to create and register custom blots. As noted in the CodePen, the main trick is getting at the right instance of Quill, which should be much easier since #159 was merged. In my particular case, the overall scheme to registering a custom blot like those Alex demoed looked like this:
```js
import ReactQuill from 'react-quill'
let Quill = ReactQuill.Quill;

let Inline = Quill.import('blots/inline');
class EmphBlot extends Inline { }
EmphBlot.blotName = 'em';
EmphBlot.tagName = 'em';
EmphBlot.className = 'custom-em';
Quill.register('formats/em', EmphBlot);
```

It's worth noting that my setup is a weird mix of transpiled ES6 and ClojureScript, so you may not want to quote me on syntax ideals, but that should help get you started.

It's worth noting that getting access to `Quill.import` is really useful because it gives you access not only to Quill's blots but to other essentials like Parchment (`Quill.import('parchment')`) and Delta (`Quill.import('delta')`) which may be necessary depending on the complexity of your custom blots.

**Closed** 2017-02-26 02:39 UTC
Labels: documentation

**Comment by Dakuan** [comment] 2017-03-09 17:23
hmm, all I get is `:_reactQuill.Quill.import is not a function`

**Comment by alexkrolick** [comment] 2017-03-09 19:50
@Dakuan would have to see a code snippet to diagnose that issue. What version are you on?

**Comment by ycjcl868** [comment] 2018-10-17 06:56
How about `formats/align`, I can't operate the `parchment`

![image](https://user-images.githubusercontent.com/13595509/47067673-bb69f200-d21c-11e8-9c2c-3d26486742dd.png)
