### ISSUE TITLE
Warning on QuillToolbar.renderChoiceItem

### ISSUE THREAD

**Issue by erKURITA** [zenoamaro/react-quill#77] opened 2016-02-10 16:28 UTC
In React 0.14.2 there's a warning in `QuillToolbar.renderChoiceItem` due to setting the `selected` property on an option, whereas the appropriate way would be to set it on the `select` instead. Removing the prop like so:

```javascript
	renderChoiceItem: function(item, key) {
		return React.DOM.option({
			key: item.label || item.value || key,
			value:item.value },
			item.label
		);
	},
```

removes the warning

**Comment by erKURITA** [comment] 2016-02-10 16:34
Looking a bit more into the code, I see that this prop is part of the toolbar structure. 

* One way to solve it would be moving the `selected` prop to the select but that might break backwards compatibility. 
* Another would be to use something similar to underscore's `pluck` to extract the `value` of the item with the `selected` prop.

**Comment by zenoamaro** [comment] 2016-02-10 16:36
Duplicate of #73, which has been merged in master.

**Closed by zenoamaro** 2016-02-10 16:36 UTC
