### ISSUE TITLE
doesnt work when rendering on the server

### ISSUE THREAD

**Issue by flyon** [zenoamaro/react-quill#348] opened 2018-04-02 21:48 UTC
When trying to render the page on the server using ReactDOM.hydrate the following error occurs:
`ReferenceError: document is not defined
at Object.DIFF_DELETE (C:\web\dacore\modules\html\node_modules\quill\dist\quill.js:7588:12)`

**Comment by alexkrolick** [comment] 2018-04-03 16:50
Duplicate of https://github.com/zenoamaro/react-quill/issues/185

**Closed by alexkrolick** 2018-04-03 16:50 UTC
